In [1]:
import numpy as np
import time

In [24]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized Implementation:" + str(1000*(toc-tic)) + "ms")

Vectorized Implementation:2.0017623901367188ms


In [25]:
c = 0
tic = time.time()
for i in range(1000000):
    c+=a[i] * b[i]
toc = time.time()

print("For Loop-Non Vectorized Implementation:" + str(1000*(toc-tic)) + "ms")

For Loop-Non Vectorized Implementation:594.6910381317139ms


In [23]:
#Almost 300Times Slower than Vectorized Version.

In [59]:
A = np.random.randn(5)  #Returns a Numpy Array which is different from a Matrix.
print(A)
np.shape(A) #Its just a Rank-1 array - Does not behave consistently either as a Row Vector or as a Col Vector

[ 0.76640006  0.62039664 -0.41548362 -0.11927308  0.43225054]


(5,)

In [60]:
print(A.T) #Transpose is not giving us proper result as its not a Matrix.
print(np.dot(A,A.T)) #Generates a scalar - Inner Product

#So we convert it using Reshape.
A = A.reshape(5,1)
print(A)

[ 0.76640006  0.62039664 -0.41548362 -0.11927308  0.43225054]
1.345954279097916
[[ 0.76640006]
 [ 0.62039664]
 [-0.41548362]
 [-0.11927308]
 [ 0.43225054]]


In [61]:
B = np.random.randn(5,1)
print(B) #Returns a 5X1 - Col Vector
print(B.T)
assert(B.shape==(5,1))

[[-1.42922865]
 [-1.71430664]
 [-0.65160029]
 [-1.29201746]
 [ 1.91415327]]
[[-1.42922865 -1.71430664 -0.65160029 -1.29201746  1.91415327]]


In [62]:
print(np.dot(B,B.T)) #Generates a outer Product

[[ 2.04269453  2.45013617  0.9312858   1.84658837 -2.73576268]
 [ 2.45013617  2.93884727  1.11704271  2.21491412 -3.28144566]
 [ 0.9312858   1.11704271  0.42458294  0.84187895 -1.24726283]
 [ 1.84658837  2.21491412  0.84187895  1.66930912 -2.47311944]
 [-2.73576268 -3.28144566 -1.24726283 -2.47311944  3.66398273]]
